"use server";

import { createClient } from "@/modules/shared/lib/supabase/server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";

export async function getCases() {
  const supabase = createClient();
  
  // 현재 로그인한 사용자 확인
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    redirect("/login");
  }

  // 현재 사용자의 케이스만 조회 (guardian_id 필터링)
  const { data: cases, error } = await supabase
    .from("cases")
    .select("*")
    .eq("guardian_id", user.id) // ⭐ 보안: 본인의 케이스만 조회
    .order("created_at", { ascending: false });

  if (error) {
    console.error("Error fetching cases:", error);
    return [];
  }

  return cases || [];
}

export async function getCase(id: string) {
  const supabase = createClient();
  
  // 현재 로그인한 사용자 확인
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    redirect("/login");
  }

  // 케이스 조회 (본인의 케이스만)
  const { data: caseData, error } = await supabase
    .from("cases")
    .select("*")
    .eq("id", id)
    .eq("guardian_id", user.id) // ⭐ 보안: 본인의 케이스만 조회
    .single();

  if (error) {
    console.error("Error fetching case:", error);
    return null;
  }

  // 간병 기간 종료 시 상태 자동 업데이트
  if (caseData && caseData.status === 'IN_PROGRESS' && caseData.caregiver_agreed_at) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const endDate = new Date(caseData.end_date_final || caseData.end_date_expected);
    endDate.setHours(0, 0, 0, 0);

    // 종료일이 지났으면 상태를 COMPLETED로 변경
    if (today > endDate) {
      const { error: updateError } = await supabase
        .from("cases")
        .update({ status: "COMPLETED" })
        .eq("id", id)
        .eq("guardian_id", user.id);

      if (!updateError) {
        caseData.status = "COMPLETED";
      }
    }
  }

  return caseData;
}

export async function createCase(formData: FormData) {
  const supabase = createClient();
  
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const patient_name = formData.get("patient_name") as string;
  const hospital_name = formData.get("hospital_name") as string;
  const diagnosis = formData.get("diagnosis") as string;
  const start_date = formData.get("start_date") as string;
  const end_date_expected = formData.get("end_date_expected") as string;
  const daily_wage = parseInt(formData.get("daily_wage") as string, 10);
  const caregiver_name = formData.get("caregiver_name") as string;
  const caregiver_contact = formData.get("caregiver_contact") as string;

  // Validation
  if (!patient_name || !start_date || !end_date_expected || isNaN(daily_wage)) {
      return { error: "필수 항목을 모두 입력해주세요." };
  }

  const start = new Date(start_date);
  const end = new Date(end_date_expected);
  const today = new Date();
  today.setHours(0, 0, 0, 0); // 시간 제거하고 날짜만 비교
  
  // 시작일은 오늘 이후여야 함
  if (start < today) {
    return { error: "시작일은 오늘 또는 미래 날짜만 선택 가능합니다." };
  }
  
  if (start > end) {
    return { error: "종료 예정일은 시작일 이후여야 합니다." };
  }

  const { data, error } = await supabase.from("cases").insert({
    guardian_id: user.id,
    patient_name,
    hospital_name,
    diagnosis,
    start_date,
    end_date_expected,
    daily_wage,
    caregiver_name,
    caregiver_contact,
    status: "GUARDIAN_PENDING",
  }).select().single();

  if (error) {
    return { error: error.message };
  }

  revalidatePath("/cases");
  redirect(`/cases/${data.id}`);
}

export async function agreeGuardian(caseId: string) {
  const supabase = createClient();
  
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  // 1. Update Case Status
  const { error: updateError } = await supabase
    .from("cases")
    .update({
      guardian_agreed_at: new Date().toISOString(),
      status: "CAREGIVER_PENDING",
    })
    .eq("id", caseId)
    .eq("guardian_id", user.id);

  if (updateError) return { error: updateError.message };

  // 2. Create Token
  const { error: tokenError } = await supabase
    .from("case_tokens")
    .insert({
      case_id: caseId,
      // token is generated by default
    });

  if (tokenError) {
     return { error: "토큰 생성 실패: " + tokenError.message };
  }

  revalidatePath(`/cases/${caseId}`);
  redirect(`/cases/${caseId}`);
}

export async function getCaseToken(caseId: string) {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return null;

    const { data, error } = await supabase
        .from("case_tokens")
        .select("token")
        .eq("case_id", caseId)
        .single();
    
    if (error) return null;
    return data?.token;
}

export async function endCaseEarly(caseId: string, newEndDate: string, caregiverConsent: boolean = false) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  // Fetch case to validate dates
  const { data: currentCase } = await supabase
    .from("cases")
    .select("start_date, end_date_expected, end_date_final")
    .eq("id", caseId)
    .single();
    
  if (!currentCase) return { error: "케이스를 찾을 수 없습니다." };

  // 간병인 동의 확인
  if (!caregiverConsent) {
    return { error: "간병인 동의가 필요합니다." };
  }

  const newEnd = new Date(newEndDate);
  const start = new Date(currentCase.start_date);
  const originalEnd = new Date(currentCase.end_date_final || currentCase.end_date_expected);
  const today = new Date();
  // Normalize dates to start of day for comparison
  today.setHours(0,0,0,0);
  newEnd.setHours(0,0,0,0);
  start.setHours(0,0,0,0);
  originalEnd.setHours(0,0,0,0);

  // 검증 1: 시작일보다 빠를 수 없음
  if (newEnd < start) {
      return { error: "종료일은 시작일보다 빠를 수 없습니다." };
  }

  // 검증 2: 기존 종료일보다 빠르거나 같아야 함 (조기종료이므로)
  if (newEnd >= originalEnd) {
      return { error: "조기 종료일은 기존 종료일보다 빠른 날짜여야 합니다." };
  }

  // 검증 3: 과거 날짜는 안됨 (오늘 이후만 가능)
  if (newEnd < today) {
      return { error: "조기 종료일은 오늘 이후 날짜만 가능합니다." };
  }

  // 1. Update Case
  const { error } = await supabase
    .from("cases")
    .update({ end_date_final: newEndDate })
    .eq("id", caseId)
    .eq("guardian_id", user.id);

  if (error) return { error: error.message };

  // 2. Inactive logs
  const { error: logError } = await supabase
    .from("care_logs")
    .update({ is_active: false })
    .eq("case_id", caseId)
    .gt("date", newEndDate);
  
  revalidatePath(`/cases/${caseId}`);
  redirect(`/cases/${caseId}`);
}

export async function extendCase(caseId: string, newEndDate: string, caregiverConsent: boolean = false) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { data: currentCase } = await supabase
    .from("cases")
    .select("end_date_expected, end_date_final")
    .eq("id", caseId)
    .single();
  
  if (!currentCase) return { error: "케이스를 찾을 수 없습니다." };

  // 간병인 동의 확인
  if (!caregiverConsent) {
    return { error: "간병인 동의가 필요합니다." };
  }

  const currentEnd = new Date(currentCase.end_date_final || currentCase.end_date_expected);
  const newEnd = new Date(newEndDate);
  
  // Normalize dates to start of day for comparison
  currentEnd.setHours(0,0,0,0);
  newEnd.setHours(0,0,0,0);

  // 검증: 기존 종료일보다 뒤여야 함 (연장이므로)
  if (newEnd <= currentEnd) {
      return { error: "연장할 종료일은 현재 종료일보다 뒤여야 합니다." };
  }

  const { error } = await supabase
    .from("cases")
    .update({ end_date_final: newEndDate })
    .eq("id", caseId)
    .eq("guardian_id", user.id);

  if (error) return { error: error.message };

  revalidatePath(`/cases/${caseId}`);
  redirect(`/cases/${caseId}`);
}

// ================================================
// 케이스 삭제 (Hard Delete with Confirm)
// ================================================
export async function deleteCase(id: string) {
  const supabase = createClient();
  
  // 1. 현재 사용자 확인
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { error: "로그인이 필요합니다." };
  }

  // 2. 케이스 소유권 확인
  const { data: caseData } = await supabase
    .from("cases")
    .select("guardian_id")
    .eq("id", id)
    .single();

  if (!caseData) {
    return { error: "케이스를 찾을 수 없습니다." };
  }

  if (caseData.guardian_id !== user.id) {
    return { error: "권한이 없습니다." };
  }

  // 3. 케이스 삭제 (CASCADE로 연관 데이터 자동 삭제)
  const { error } = await supabase
    .from("cases")
    .delete()
    .eq("id", id)
    .eq("guardian_id", user.id); // 추가 보안

  if (error) {
    console.error("케이스 삭제 에러:", error);
    return { error: "삭제에 실패했습니다. 다시 시도해주세요." };
  }

  revalidatePath("/cases");
  return { success: true };
}
